# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nathan Hanson
email: nmhanson23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Hey! I'm currently a super-senior studying Software Engineering at Iowa State.
    I will graduate this December if I don't fail any classes! I've had fair amount of
    experience with web development; I currently work at Iowa State as a web developer,
    and I contributed to a web application with Cerner in Kansas City. I am not just
    a web developer though! I have recently become much more interested in programming as more than 
    just a career, but as a fun hobby and
    tool for personal use. Thanks for checking out my site, please ignore the bugs 
    and other eyesores - I am not a designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nmhanson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: nmhanson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
