title: Nathan Hanson
email: nmhanson23@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Hello!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nmhanson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: nmhanson

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
